[package]
name = "protocol"
version = "0.1.0"
authors = ["Ryan Wicks <ryancwicks@gmail.com>"]
edition = "2018"

[dependencies]
postcard = "0.5.2"
serde = {version = "1.0", default_features=false, features=["derive"]}
heapless = "0.5.4"
